//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectGrade
    {
        public int ID { get; set; }
        public string StuNo { get; set; }
        public int Grade { get; set; }
        public int ProjectItemID { get; set; }
        public System.DateTime GradeDT { get; set; }
        public string ReviewStuNo { get; set; }
    
        public virtual ProjectItem ProjectItem { get; set; }
        public virtual Student Student { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
