//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectView.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectReviewDBEntities : DbContext
    {
        public ProjectReviewDBEntities()
            : base("name=ProjectReviewDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Class> Classes { get; set; }
        public DbSet<ClassReviewProject> ClassReviewProjects { get; set; }
        public DbSet<ProjectGrade> ProjectGrades { get; set; }
        public DbSet<ProjectItem> ProjectItems { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentUser> StudentUsers { get; set; }
        public DbSet<TeacherRemark> TeacherRemarks { get; set; }
        public DbSet<Teacher> Teachers { get; set; }
        public DbSet<TeacherUser> TeacherUsers { get; set; }
    }
}
