//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectItem
    {
        public ProjectItem()
        {
            this.ProjectGrades = new HashSet<ProjectGrade>();
        }
    
        public int ID { get; set; }
        public string ItemName { get; set; }
        public int Grade { get; set; }
        public int ProjectID { get; set; }
    
        public virtual ICollection<ProjectGrade> ProjectGrades { get; set; }
        public virtual Project Project { get; set; }
    }
}
