//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.ProjectGrades = new HashSet<ProjectGrade>();
            this.ProjectGrades1 = new HashSet<ProjectGrade>();
            this.TeacherRemarks = new HashSet<TeacherRemark>();
        }
    
        public string StuNo { get; set; }
        public string StuName { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Contact { get; set; }
        public string PersonID { get; set; }
        public int ClassID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<ProjectGrade> ProjectGrades { get; set; }
        public virtual ICollection<ProjectGrade> ProjectGrades1 { get; set; }
        public virtual StudentUser StudentUser { get; set; }
        public virtual ICollection<TeacherRemark> TeacherRemarks { get; set; }
    }
}
